### ISSUE TITLE
New output: CSV/TSV format for pasting into google sheet

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/ValueSet-Converters#4]

**Comment by Sigfried** [comment]
Is this done? @stephanieshong? What do you think?

**Comment by Sigfried** [comment]
From @DaveraGabriel:  when its possible to add the VSAC name to each row that would be handy Im about to dive in and manually dril / copy each of these

**Comment by joeflack4** [comment]
I think we finished the first version on Friday. For any additions, let's create new issues
