### ISSUE TITLE
please add name column

### ISSUE THREAD

**Issue by stephanieshong** [HOT-Ecosystem/ValueSet-Converters#7]

**Comment by stephanieshong** [comment]
Could the name column be the first column right next to the OID column. Hard to scroll to the end when the code list is very long

**Comment by joeflack4** [comment]
We now have a name field at the very left. Here's an example CSV output: https://docs.google.com/spreadsheets/d/1jzGrVELQz5L4B_-DqPflPIcpBaTfJOUTrVJT5nS_j18/edit#gid=1091853371
